name: HotelPlugin
version: 1.4.0
main: com.yourname.hotelplugin.HotelPlugin
api-version: 1.20
author: yosi_game & itsmelody18
description: A hotel management plugin for DreamCraft Parks
softdepend: [Vault] # <-- Moved softdepend to the correct top-level position

commands:
  hotel:
    description: Main command for Hotel Plugin.
    # IMPORTANT: Remove the 'permission' key here.
    # We will handle permissions for each *subcommand* in your Java code (HotelCommand.java).
    # If a permission is set here, it applies to *all* subcommands by default,
    # preventing non-ops from even typing /hotel buy.
    usage: |
      /hotel buy <roomID> - Purchase an available hotel room.
      /hotel release <roomID> - Release your owned hotel room.
      /hotel info [roomID] - View room details (your own, or any if admin).
      /hotel list - List available hotel rooms.
      /hotel setroom <roomID> <price> [currency] [description] - Admin: Set up a new room.
      /hotel remove <roomID> - Admin: Forcibly remove a room from the plugin.
      /hotel reload - Admin: Reload plugin configuration.
    aliases: [ ht ]

permissions:
  # Player Permissions (default: true means all players have these by default)
  hotelplugin.buy:
    description: Allows players to buy hotel rooms.
    default: true
  hotelplugin.release:
    description: Allows players to release their own hotel rooms.
    default: true
  hotelplugin.info:
    description: Allows players to view information about their own room.
    default: true
  hotelplugin.list:
    description: Allows players to list available hotel rooms.
    default: true

  # Admin Permissions (default: op means only OPs have these by default)
  # It's good practice to have a parent admin permission, and then specific ones as children.
  hotelplugin.admin:
    description: Parent permission for all administrative commands for HotelPlugin.
    default: op
    children:
      hotelplugin.admin.setroom: true
      hotelplugin.admin.remove: true
      hotelplugin.admin.info_others: true # For admin to get info on *any* room
      hotelplugin.admin.list_all: true    # For admin to list *all* rooms (occupied and available)
      hotelplugin.admin.reload: true